"""workbooks and sheets

Revision ID: 084041f36aa3
Revises: e4f26272f1de
Create Date: 2026-06-27 13:18:24.370808
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = '084041f36aa3'
down_revision: str | None = 'e4f26272f1de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workbooks',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_workbook_company_name')
    )
    with op.batch_alter_table('workbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbooks_company_id'), ['company_id'], unique=False)

    op.create_table('sheets',
    sa.Column('workbook_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workbook_id', 'name', name='uq_sheet_workbook_name')
    )
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheets_workbook_id'), ['workbook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheets_workbook_id'))

    op.drop_table('sheets')
    with op.batch_alter_table('workbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbooks_company_id'))

    op.drop_table('workbooks')
    # ### end Alembic commands ###
