"""bank accounts and statement lines

Revision ID: 5a5a1d240f06
Revises: 084041f36aa3
Create Date: 2026-06-27 13:58:32.618556
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = '5a5a1d240f06'
down_revision: str | None = '084041f36aa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('gl_account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=34), nullable=True),
    sa.Column('sort_code', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gl_account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_bank_account_company_name')
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('bank_statement_lines',
    sa.Column('bank_account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('line_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('money_out_minor', sa.BigInteger(), nullable=False),
    sa.Column('money_in_minor', sa.BigInteger(), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('posted_journal_id', sa.Uuid(), nullable=True),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'content_hash', name='uq_statement_line_hash')
    )
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_is_posted'), ['is_posted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_is_posted'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_bank_account_id'))

    op.drop_table('bank_statement_lines')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_accounts_company_id'))

    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
