"""fixed assets

Revision ID: 663adffe2cb6
Revises: b3617c64ec43
Create Date: 2026-06-27 17:26:51.403238
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = '663adffe2cb6'
down_revision: str | None = 'b3617c64ec43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('acquired_on', sa.Date(), nullable=False),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('residual_minor', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('useful_life_periods', sa.Integer(), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('asset_account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('accumulated_account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('expense_account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('accumulated_depreciation_minor', sa.BigInteger(), nullable=False),
    sa.Column('periods_depreciated', sa.Integer(), nullable=False),
    sa.Column('disposed', sa.Boolean(), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['accumulated_account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixed_assets_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixed_assets_company_id'))

    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
