"""initial foundational tables

Revision ID: a653cb20b5c9
Revises: 
Create Date: 2026-06-18 08:09:04.323008
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ledgerline_backend.db.base

revision: str = 'a653cb20b5c9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint(
        "kind IN ('business', 'accounting_firm')", name='ck_organisation_kind'
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('org_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('accounts_type', sa.String(length=32), nullable=False),
    sa.Column('companies_house_no', sa.String(length=16), nullable=True),
    sa.Column('vat_registration_no', sa.String(length=16), nullable=True),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint(
        "accounts_type IN ('sole_trader', 'partnership', 'ltd', 'micro', 'small')",
        name='ck_company_accounts_type',
    ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('org_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint(
        "status IN ('active', 'invited', 'suspended', 'disabled')",
        name='ck_user_status',
    ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_org_id'), ['org_id'], unique=False)

    op.create_table('accounting_periods',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("ends_on > starts_on", name='ck_period_dates'),
    sa.CheckConstraint(
        "status IN ('open', 'soft_closed', 'locked')", name='ck_period_status'
    ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', name='uq_period_company_year')
    )
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_periods_company_id'), ['company_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=True),
    sa.Column('actor_user_id', ledgerline_backend.db.base.GUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('prev_hash', sa.LargeBinary(), nullable=True),
    sa.Column('this_hash', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('chart_of_accounts',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('normal_balance', sa.String(length=2), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('control_kind', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint(
        "account_type IN ('asset', 'liability', 'equity', 'income', 'expense')",
        name='ck_coa_account_type',
    ),
    sa.CheckConstraint("normal_balance IN ('DR', 'CR')", name='ck_coa_normal_balance'),
    sa.CheckConstraint(
        "control_kind IS NULL OR control_kind IN ('bank', 'debtors', 'creditors', 'vat')",
        name='ck_coa_control_kind',
    ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_coa_company_code')
    )
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('sync_events',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('server_seq', sa.BigInteger(), nullable=True),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('hlc_wall', sa.BigInteger(), nullable=False),
    sa.Column('hlc_counter', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', ledgerline_backend.db.base.GUID(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('causation_id', sa.Uuid(), nullable=True),
    sa.Column('prev_hash', sa.LargeBinary(), nullable=True),
    sa.Column('this_hash', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_seq', name='uq_sync_event_server_seq')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_events_correlation_id'), ['correlation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_sync_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_sync_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_sync_events_aggregate_id'))

    op.drop_table('sync_events')
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_company_id'))

    op.drop_table('chart_of_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('accounting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_periods_company_id'))

    op.drop_table('accounting_periods')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_org_id'))

    op.drop_table('users')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_org_id'))

    op.drop_table('companies')
    op.drop_table('organisations')
    # ### end Alembic commands ###
