"""vat code on journal lines

Revision ID: a9cce13a14bc
Revises: ec1fe5ad0db8
Create Date: 2026-06-27 15:18:28.066175
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base  # noqa: F401

revision: str = 'a9cce13a14bc'
down_revision: str | None = 'ec1fe5ad0db8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_code', sa.String(length=8), nullable=True))
        # server_default backfills existing rows; the ORM default keeps new rows 0.
        batch_op.add_column(
            sa.Column('vat_minor', sa.BigInteger(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_column('vat_minor')
        batch_op.drop_column('vat_code')

    # ### end Alembic commands ###
