"""vat return submissions

Revision ID: b3617c64ec43
Revises: a9cce13a14bc
Create Date: 2026-06-27 16:17:11.056786
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = 'b3617c64ec43'
down_revision: str | None = 'a9cce13a14bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat_return_submissions',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('box1_minor', sa.BigInteger(), nullable=False),
    sa.Column('box2_minor', sa.BigInteger(), nullable=False),
    sa.Column('box3_minor', sa.BigInteger(), nullable=False),
    sa.Column('box4_minor', sa.BigInteger(), nullable=False),
    sa.Column('box5_minor', sa.BigInteger(), nullable=False),
    sa.Column('box6_minor', sa.BigInteger(), nullable=False),
    sa.Column('box7_minor', sa.BigInteger(), nullable=False),
    sa.Column('box8_minor', sa.BigInteger(), nullable=False),
    sa.Column('box9_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vat_return_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_return_submissions_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat_return_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_return_submissions_company_id'))

    op.drop_table('vat_return_submissions')
    # ### end Alembic commands ###
