"""hmrc mtd tokens and submission state

Revision ID: d60cb5aa4060
Revises: 663adffe2cb6
Create Date: 2026-06-27 18:24:02.277223
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = 'd60cb5aa4060'
down_revision: str | None = '663adffe2cb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmrc_tokens',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_hmrc_token_company')
    )
    with op.batch_alter_table('hmrc_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hmrc_tokens_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('vat_return_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hmrc_status', sa.String(length=16), server_default='not_submitted', nullable=False))
        batch_op.add_column(sa.Column('hmrc_period_key', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('hmrc_form_bundle', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('hmrc_charge_ref', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('hmrc_receipt_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vat_return_submissions', schema=None) as batch_op:
        batch_op.drop_column('hmrc_receipt_at')
        batch_op.drop_column('hmrc_charge_ref')
        batch_op.drop_column('hmrc_form_bundle')
        batch_op.drop_column('hmrc_period_key')
        batch_op.drop_column('hmrc_status')

    with op.batch_alter_table('hmrc_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hmrc_tokens_company_id'))

    op.drop_table('hmrc_tokens')
    # ### end Alembic commands ###
