"""journals and journal lines

Revision ID: e4f26272f1de
Revises: 7e313d86064e
Create Date: 2026-06-27 13:04:57.721134
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = 'e4f26272f1de'
down_revision: str | None = '7e313d86064e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('period_id', ledgerline_backend.db.base.GUID(), nullable=True),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('journal_type', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('narrative', sa.String(length=1024), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Uuid(), nullable=True),
    sa.Column('reverses_journal_id', sa.Uuid(), nullable=True),
    sa.Column('reversed_by_journal_id', sa.Uuid(), nullable=True),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journals_is_posted'), ['is_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_journals_period_id'), ['period_id'], unique=False)

    op.create_table('journal_lines',
    sa.Column('journal_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('debit_minor', sa.BigInteger(), nullable=False),
    sa.Column('credit_minor', sa.BigInteger(), nullable=False),
    sa.Column('base_debit_minor', sa.BigInteger(), nullable=False),
    sa.Column('base_credit_minor', sa.BigInteger(), nullable=False),
    sa.Column('narrative', sa.String(length=512), nullable=True),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('debit_minor >= 0 AND credit_minor >= 0', name='ck_line_non_negative'),
    sa.CheckConstraint(
        'NOT (debit_minor > 0 AND credit_minor > 0)', name='ck_line_debit_xor_credit'
    ),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'line_no', name='uq_journal_line_no')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_journal_id'), ['journal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_journal_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_period_id'))
        batch_op.drop_index(batch_op.f('ix_journals_is_posted'))
        batch_op.drop_index(batch_op.f('ix_journals_company_id'))

    op.drop_table('journals')
    # ### end Alembic commands ###
