"""bank reconciliation marks

Revision ID: ec1fe5ad0db8
Revises: 5a5a1d240f06
Create Date: 2026-06-27 14:56:42.332875
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = 'ec1fe5ad0db8'
down_revision: str | None = '5a5a1d240f06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliation_marks',
    sa.Column('bank_account_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('journal_line_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_line_id'], ['journal_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_account_id', 'journal_line_id', name='uq_recon_mark_account_line')
    )
    with op.batch_alter_table('bank_reconciliation_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_reconciliation_marks_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_reconciliation_marks_journal_line_id'), ['journal_line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_reconciliation_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_reconciliation_marks_journal_line_id'))
        batch_op.drop_index(batch_op.f('ix_bank_reconciliation_marks_bank_account_id'))

    op.drop_table('bank_reconciliation_marks')
    # ### end Alembic commands ###
