"""company memberships

Revision ID: f1227cec12db
Revises: ef1cee08ba88
Create Date: 2026-06-18 10:17:50.296557
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Always available so autogenerated references to the portable GUID type
# (rendered as ledgerline_backend.db.base.GUID) resolve. Unused in some
# migrations, hence the noqa.
import ledgerline_backend.db.base

revision: str = 'f1227cec12db'
down_revision: str | None = 'ef1cee08ba88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_memberships',
    sa.Column('user_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('company_id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', ledgerline_backend.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint(
        "role IN ('owner', 'accountant', 'bookkeeper', 'readonly')",
        name='ck_membership_role',
    ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_membership_user_company')
    )
    with op.batch_alter_table('company_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_memberships_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_memberships_company_id'))

    op.drop_table('company_memberships')
    # ### end Alembic commands ###
